run_unittests:
  image: continuumio/miniconda3
  before_script:
#    - pip install pytest mock pytest-mock paramiko
    - conda env create -f conda/intorods.yaml
  script:
    - source activate intorods
    - cd test
    - pytest .
