run_unittests:
  image: continuumio/miniconda3
  before_script:
    - conda env create -f conda/intorods.yaml
    - source activate intorods
    - pip install pytest pytest-mock mock
  script:
    - source activate intorods
    - cd test
    - pytest .
